{% set name = "papermill" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6dc195f2a52f5bed8d4292ccea39af0f3338324beafd56290f9616c95033623

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - ansiwrap
    - black
    - click
    - entrypoints
    - nbclient >=0.2.0
    - nbformat
    - python >=3.6
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2

test:
  imports:
    - papermill
  commands:
    - papermill --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nteract/papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks.
  doc_url: http://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
