{% set name = "papermill" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # FIXME: Revert GitHub archive change when sdist is correctly packaged
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/nteract/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ec3d6ae68e56c1824497bb0155f97297842bd26e27e33df2eb62ddb1f67a021d

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - aiohttp >=3.9
    - click
    - entrypoints
    - nbclient >=0.2.0
    - nbformat >=5.2.0
    - python >={{ python_min }}
    - pyyaml
    - requests
    - tenacity >=5.0.2
    - tqdm >=4.32.2

test:
  imports:
    - papermill
  commands:
    - papermill --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/nteract/papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks.
  doc_url: http://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - dhirschfeld
    - MSeal
    - willingc
