{% set name = "papermill" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10f86551cd28d09acea1f63b04a61d061ed4c3d3e82aa675b6a593c4451860c6

build:
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: true  # [py<35]

requirements:
  host:
    - ansiwrap
    - click
    - entrypoints
    - jupyter_client
    - nbclient >=0.2.0
    - nbformat
    - pip
    - python
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2
    - black
  run:
    - ansiwrap
    - click
    - entrypoints
    - jupyter_client
    - nbclient >=0.2.0
    - nbformat
    - pip
    - python
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2
    - black

test:
  imports:
    - papermill
  commands:
    - papermill --help

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Papermill parameterizes, executes, and analyzes Jupyter Notebooks."
  doc_url: http://papermill.readthedocs.io/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - MSeal
    - willingc
