{% set name = "papermill" %}
{% set version = "0.14.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "60a282ffdcc14ae427a85a12fbd856885716010ef691066f2f1957e5904be52d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - papermill = papermill.cli:papermill
  
requirements:
  home:
    - python
    - pip >=9.0.1

  run:
    - python
    - ansiwrap
    - boto3
    - click
    - future
    - futures  # [py2k]
    - ipython >=5.0
    - pyyaml
    - nbformat
    - nbconvert
    - six
    - tqdm
    - jupyter_client
    - pandas
    - requests

test:
  imports:
    - papermill
  commands:
    - papermill --help

about:
  home: https://github.com/nteract/papermill
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Papermill is a tool for parameterizing, executing, and analyzing Jupyter Notebooks.'
  doc_url: http://papermill.readthedocs.io/en/latest/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - pmlandwehr
