{% set name = "papermill" %}
{% set version = "0.19.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "60a282ffdcc14ae427a85a12fbd856885716010ef691066f2f1957e5904be52d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - papermill = papermill.cli:papermill

requirements:
  host:
    - python
    - pip >=9.0.1

  run:
    - python
    - virtualenv >=1.11.2

test:
  imports:
    - tox

  commands:
    - tox -e py{{ environ.get('PY_VER').replace('.', '') }}

about:
  home: https://github.com/nteract/papermill
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Papermill is a tool for parameterizing, executing, and analyzing Jupyter Notebooks.'
  doc_url: http://papermill.readthedocs.io/en/latest/
  dev_url: https://github.com/nteract/papermill

extra:
  recipe-maintainers:
    - mseal
