appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Az1GGrWr++yFl5mI37ahXF5LgKTrHdjF8FIB5BxVapzECdnFPLkwY6Xd+J81W8hu9sMQaX4X7QcmYd4/iVC5JqeTxrVPTkTfQtXM0UYfP5F1iKvNvDk3XUCWajsXeEyYISF/T2cvZ1T8o+l4KmKLxf261K58UZrfU8VAGWPvKJOEQTFiqbUrPqBX/g1mUCK9s+kmzVuQ3Oo3HWgDfAaOa1jic1+XSSQmSzB8rlx+2UVztKRBtYvNIz3BGfVPkeVaYeGL5+xI8pdtpedFiO9cLBJnfN5m822c0Mu7F6QmaFx41i2S1iJXZ2/c/a+mWl+NmQkK6q2eea0o3djWXgrm+qhbiSUeUP2t5eJCBLuIXm2phE5x6Pgpy7MWCa+ZMoTZ+WbwzbsMmEA5PO700uCYy5kZkNvSt+QSQlxejZUKjBldx3tENTbp4gnEOPunNasR0q1vOADC+L46ATPt/UmdLmXGANTbN1A9m6gyoX7ZhDUMG0J6tpbm3GKj0GZM+u5XRLP9BllG1cUOtmA654nxoUbQpJPkmPN/NkJxE33BygextCHTqqNDim0qQXjvfqBaXtV/fffX6XiJOtPsYVYTBnFCWxCz0iDfpaU6aTcA4yB2trmytsCB4dEDOQ1e1KoqaWXi8/haqoeDWuMlrO8rNHsNrD4rXV9Kg6Ppkf02GJg=}
provider:
  win: azure
conda_forge_output_validation: true
